version: '3'
services:
  # Mongodb Container
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123

  # Node container
  api: 
    build: .
    ports:
      - "8080:5000"
    volumes:
      -.: /usr/src/app
    depends_on:
      - mongo_db

volumes: 
  mongo_db: {}
