version: "3.8"
services:
  #Mongodb container
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports: 
      - "27017:27017"
    volumes: 
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: Admin123

  #Node container
  backend_node:
    container_name: backend
    build: .
    ports:
      - "8080:5000"
    volumes:
      - node_db:/data/db
    depends_on:
      - mongo_db

volumes:
  mongo_db: 
  node_db: 
